### ISSUE TITLE
Studio cannot interpret correctly local time zone

### ISSUE THREAD

**Issue by adamkk** [isaacfab/RMetalog#1]
Dear Isaac,

During install from GitHub there is a warning message: in command strptime(x, fmt, tz = "GMT")':
  unknown timezone 'zone/tz/2017c.1.0/zoneinfo/Europe/Warsaw'

Perhaps, it is an issue with R itself. My versions latest as of today: R version 3.4.2 (2017-09-28) -- "Short Summer"

best,
Adam

**Comment by isaacfab** [comment]
Adam,

Thank you, I will look into it.

**Comment by isaacfab** [comment]
I have tried to replicate the problem with no luck. Are you using the most recent version of the devtools package?

**Comment by adamkk** [comment]
Dear Isaac,

problem resolved as I have updated RStudio to Version 1.1.383 – and R system to R version 3.4.3 (2017-11-30) -- "Kite-Eating Tree" today.
Best,
