### ISSUE TITLE
Fit to moments?

### ISSUE THREAD

**Issue by bensprung** [isaacfab/RMetalog#11]
This is really just a question--I see that `metalog()` takes numeric data to fit to. Is there any way to fit a metalog distribution to the first N (raw) moments, rather than to data? I have moments but not data. Thanks!

**Comment by isaacfab** [comment]
Good question. The `metalog` distribution is empirically driven with a focus on flexibility to fit many high order moments (in the metalog the number of terms is analogous to moments). However, if you have moments you can parameterize a distribution by creating data that match them (then fitting a metalog) but it would be tricky and is not implemented in this package.
