### ISSUE TITLE
Does not pass through quantiles exactly

### ISSUE THREAD

**Issue by tadamcz** [isaacfab/RMetalog#13]
Hi and thank you for building rmetalog.

When the number of quantiles provided by the user equals number of terms, the metalog should pass through the quantiles exactly ([source](http://www.metalogdistributions.com/images/The_Metalog_Distributions_-_Keelin_2016.pdf)):

> How many terms to use depends significantly
on purpose and context. For example, in decision
analysis applications with three assessed data points
(m = 3), it is natural to use three terms (n = 3). In
this case, for any feasible data, the metalog CDF will
pass through these data points exactly as illustrated in
Figure 14. More generally, the metalog distributions
will pass through the data exactly whenever n = m
and the data is feasible, so it makes sense to start with
n = m when this result is desired.

However, this doesn't always work for me with rmetalog. For example:
```R
library(rmetalog)
q = c(50,70,75,120,150)
p = c(0.1,0.5,0.6,0.7,0.8)
len = as.numeric(length(q))
metalogobj = metalog(x=q,probs=p, term_limit = len)
qmetalog(metalogobj,y=p,term=len)
```
should return back, 50,70,75,120,150, but instead returns

```
[1]  50.00000  70.00000  88.43506 114.92030 150.00000
```

Any idea what might be going on? I think it may be to do with the 0.5 and 0.6 quantiles being close together (relative to the other points) in this example.

Thanks.

**Comment by isaacfab** [comment]
Tom, sometimes the metalog is infeasible when passing through all the points (violates a rule that probability distributions must follow to be valid). If you look at a summary of the rmetalog object it will tell you the fit method. If it is OLS then it should pass through all the points. However, if it is a linear program then the object is the closest feasible metalog fit to the data.

**Comment by tadamcz** [comment]
Thanks! What rule do these quantiles violate? The cdf I specified is an increasing function, not sure what else I'm missing. :)

**Comment by isaacfab** [comment]
Good question. Even though the empirical inputs are increasing the OLS metalog fit to the data may not be. Why and when this happens is still an area of active research.

**Comment by tadamcz** [comment]
What's the fit method for the linear program? Is it minimizing the square distance between the metalog cdf and the quantiles?

**Comment by isaacfab** [comment]
Sorry for the delay! It is minimizing the absolute differences.

**Comment by tadamcz** [comment]
Cool, thanks! (I thought that's what the "linear" in linear program might mean, but it was hard to find an accessible explanation).
