### ISSUE TITLE
rHDR

### ISSUE THREAD

**Issue by dmi3kno** [isaacfab/RMetalog#9]
Doug Hubbard's HDR random number generator might fit well here with this package(especially given how much Doug and Tom are moving ahead together with Sam). I implemented it in R for seeds of up to 5 dimensions (as described in Doug [here](https://www.researchgate.net/publication/338824184_A_Multi-Dimensional_Counter-Based_Pseudo_Random_Number_Generator_as_a_Standard_for_Monte_Carlo_Simulations)) and properly documented it. Would you like a PR?

**Comment by isaacfab** [comment]
Yes, RP's always welcome :) It would be good to have Doug's work incorporated here.

**Comment by isaacfab** [comment]
Merge complete.
